# Generated by Django 4.2.7 on 2023-11-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='usertype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
